name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Checkout    
        uses: actions/checkout@v2   
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_IP}}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd ~/work/lenjoy_client && yarn build && pm2 restart client
        # ...deployment-specific steps
